name: agri_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - opencv
  - pillow
  - tensorflow
  - keras
  - scikit-image
  - imageio
  - h5py
  - requests
  - tqdm
  - beautifulsoup4
